### PR TITLE
testing.md created

### LINKED ISSUE #1: Investigate test runner / suite
It is better start with testing before we implement any logic

investigate a testing library
- unit testing
- code coverage
- e2e
- integration

lets discuss our testing approach in comments/discord

### PR DESCRIPTION
**Pull request by caglarcercinli**

### CODE REVIEW

**Comment by KerimCETINBAS** [comment]
@caglarcercinli  we can use fake api for mock data ie faker, etc

**Comment by KerimCETINBAS** [comment]
#7  basic tutorial added for testify

**Comment by caglarcercinli** [comment]
> @caglarcercinli we can use fake api for mock data ie faker, etc

during the unit testing I assume?

**Comment by KerimCETINBAS** [comment]
> > @caglarcercinli we can use fake api for mock data ie faker, etc
> 
> during the unit testing I assume?

for testing or when we need mock records during development, i do like working on a data which look like actual data

https://github.com/jaswdr/faker
https://github.com/go-faker/faker

**Review by KerimCETINBAS — APPROVED** [review]

**Pull request merged**
